package com.tphy.hospitaldoctor.ui.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CASIGN_USER_STATUS".
*/
public class CASignUserStatusDao extends AbstractDao<CASignUserStatus, String> {

    public static final String TABLENAME = "CASIGN_USER_STATUS";

    /**
     * Properties of entity CASignUserStatus.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Czydm = new Property(0, String.class, "czydm", true, "CZYDM");
        public final static Property Msspid = new Property(1, String.class, "msspid", false, "MSSPID");
        public final static Property Yxbz = new Property(2, String.class, "yxbz", false, "YXBZ");
        public final static Property Username = new Property(3, String.class, "username", false, "USERNAME");
        public final static Property Cert = new Property(4, String.class, "cert", false, "CERT");
        public final static Property Active_time = new Property(5, String.class, "active_time", false, "ACTIVE_TIME");
    }


    public CASignUserStatusDao(DaoConfig config) {
        super(config);
    }
    
    public CASignUserStatusDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CASIGN_USER_STATUS\" (" + //
                "\"CZYDM\" TEXT PRIMARY KEY NOT NULL ," + // 0: czydm
                "\"MSSPID\" TEXT," + // 1: msspid
                "\"YXBZ\" TEXT," + // 2: yxbz
                "\"USERNAME\" TEXT," + // 3: username
                "\"CERT\" TEXT," + // 4: cert
                "\"ACTIVE_TIME\" TEXT);"); // 5: active_time
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_CASIGN_USER_STATUS_CZYDM ON \"CASIGN_USER_STATUS\"" +
                " (\"CZYDM\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CASIGN_USER_STATUS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CASignUserStatus entity) {
        stmt.clearBindings();
 
        String czydm = entity.getCzydm();
        if (czydm != null) {
            stmt.bindString(1, czydm);
        }
 
        String msspid = entity.getMsspid();
        if (msspid != null) {
            stmt.bindString(2, msspid);
        }
 
        String yxbz = entity.getYxbz();
        if (yxbz != null) {
            stmt.bindString(3, yxbz);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(4, username);
        }
 
        String cert = entity.getCert();
        if (cert != null) {
            stmt.bindString(5, cert);
        }
 
        String active_time = entity.getActive_time();
        if (active_time != null) {
            stmt.bindString(6, active_time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CASignUserStatus entity) {
        stmt.clearBindings();
 
        String czydm = entity.getCzydm();
        if (czydm != null) {
            stmt.bindString(1, czydm);
        }
 
        String msspid = entity.getMsspid();
        if (msspid != null) {
            stmt.bindString(2, msspid);
        }
 
        String yxbz = entity.getYxbz();
        if (yxbz != null) {
            stmt.bindString(3, yxbz);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(4, username);
        }
 
        String cert = entity.getCert();
        if (cert != null) {
            stmt.bindString(5, cert);
        }
 
        String active_time = entity.getActive_time();
        if (active_time != null) {
            stmt.bindString(6, active_time);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public CASignUserStatus readEntity(Cursor cursor, int offset) {
        CASignUserStatus entity = new CASignUserStatus( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // czydm
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // msspid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // yxbz
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // username
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // cert
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // active_time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CASignUserStatus entity, int offset) {
        entity.setCzydm(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setMsspid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setYxbz(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUsername(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCert(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setActive_time(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final String updateKeyAfterInsert(CASignUserStatus entity, long rowId) {
        return entity.getCzydm();
    }
    
    @Override
    public String getKey(CASignUserStatus entity) {
        if(entity != null) {
            return entity.getCzydm();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CASignUserStatus entity) {
        return entity.getCzydm() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
