package com.tphy.hospitaldoctor.ui.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tphy.hospitaldoctor.ui.dao.CASignUserStatus;

import com.tphy.hospitaldoctor.ui.dao.CASignUserStatusDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cASignUserStatusDaoConfig;

    private final CASignUserStatusDao cASignUserStatusDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cASignUserStatusDaoConfig = daoConfigMap.get(CASignUserStatusDao.class).clone();
        cASignUserStatusDaoConfig.initIdentityScope(type);

        cASignUserStatusDao = new CASignUserStatusDao(cASignUserStatusDaoConfig, this);

        registerDao(CASignUserStatus.class, cASignUserStatusDao);
    }
    
    public void clear() {
        cASignUserStatusDaoConfig.clearIdentityScope();
    }

    public CASignUserStatusDao getCASignUserStatusDao() {
        return cASignUserStatusDao;
    }

}
